export const SEO_KEYWORDS = {
  GENERAL: [
    'chapada diamantina',
    'chapada diamantina bahia',
    'turismo chapada diamantina',
    'viajar para chapada diamantina',
    'viagem chapada diamantina',
    'parque nacional chapada diamantina',
    'parque nacional da chapada diamantina',
    'turismo natureza bahia',
    'ecoturismo chapada diamantina',
    'ecoturismo brasil',
    'turismo ecológico bahia',
    'turismo sustentável chapada diamantina',
    'natureza chapada diamantina',
    'paisagens chapada diamantina',
    'aventura chapada diamantina',
    'turismo aventura chapada diamantina',
    'destino natureza brasil',
    'viagem de aventura brasil',
    'destinos naturais brasil',
    'turismo aventura bahia'
  ],
  LOCATION: [
    'lençóis bahia',
    'turismo em lençóis bahia',
    'passeios em lençóis bahia',
    'agência de turismo lençóis',
    'guia turístico lençóis',
    'viagem para lençóis bahia',
    'hospedagem em lençóis',
    'hotéis em lençóis bahia',
    'pousadas em lençóis bahia',
    'roteiro lençóis bahia',
    'o que fazer em lençóis bahia',
    'chapada diamantina lençóis',
    'hospedagem lençóis bahia',
    'viagem para lençóis bahia',
    'mucugê',
    'ibicoara',
    'andaraí',
    'vale do capão',
    'igatu',
    'turismo em mucugê',
    'turismo em ibicoara',
    'turismo no vale do capão',
    'turismo em igatu'
  ],
  SERVICES: [
    'agência de turismo chapada diamantina',
    'guia chapada diamantina',
    'guia local chapada diamantina',
    'guia credenciado chapada diamantina',
    'guia turístico chapada diamantina',
    'passeios guiados chapada diamantina',
    'pacotes chapada diamantina',
    'pacote turístico chapada diamantina',
    'pacote viagem chapada diamantina',
    'expedição chapada diamantina',
    'excursão chapada diamantina',
    'tour chapada diamantina',
    'roteiro guiado chapada diamantina',
    'viagem organizada chapada diamantina',
    'agência receptiva chapada diamantina',
    'passeios chapada diamantina'
  ],
  TREKKING: [
    'trekking chapada diamantina',
    'trekking vale do pati',
    'trilhas chapada diamantina',
    'hiking chapada diamantina',
    'caminhada chapada diamantina',
    'travessia vale do pati',
    'trekking guiado chapada diamantina',
    'trekking vale do pati 2 dias',
    'trekking vale do pati 3 dias',
    'trekking vale do pati 4 dias',
    'trekking vale do pati 5 dias',
    'trekking vale do pati 6 dias',
    'travessia chapada diamantina',
    'trekking parque nacional chapada diamantina',
    'trilhas famosas chapada diamantina'
  ],
  WATERFALLS: [
    'cachoeiras chapada diamantina',
    'cachoeira da fumaça trilha',
    'cachoeira do buracão ibicoara',
    'cachoeira fumacinha trilha',
    'cachoeira do sossego trilha',
    'cachoeira do mosquito lençóis',
    'cachoeira do riachinho',
    'cachoeira da primavera',
    'cachoeira da purificação',
    'cachoeira do funil',
    'cachoeira da fumaça',
    'cachoeirão por cima',
    'cachoeira do buracão',
    'cachoeira fumacinha',
    'cachoeira da fumaça por baixo',
    'cachoeira do sossego',
    'cachoeira da primavera',
    'cachoeira do mosquitos',
    'cachoeira da purificação'
  ],
  CAVES_POOLS: [
    'poço azul chapada diamantina',
    'poço encantado',
    'gruta da lapa doce',
    'gruta da pratinha',
    'pratinha chapada diamantina',
    'gruta azul chapada diamantina',
    'grutas chapada diamantina',
    'cavernas chapada diamantina',
    'poço azul',
    'poço encantado'
  ],
  ATTRACTIONS: [
    'vale do pati',
    'morro do pai inácio',
    'cachoeira da fumaça',
    'cachoeira do buracão',
    'cachoeira da fumacinha',
    'poço azul',
    'poço encantado',
    'gruta da lapa doce',
    'pratinha',
    'cachoeira do mosquito',
    'cachoeira do sossego',
    'cachoeirão por cima',
    'morro do camelo',
    'serra do sincora',
    'mirantes chapada diamantina',
    'paisagens chapada diamantina',
    'natureza chapada diamantina',
    'fotografia chapada diamantina'
  ],
  SPECIFIC_TOURS: [
    'passeio vale do pati',
    'passeio cachoeira da fumaça',
    'passeio buracão',
    'passeio fumacinha',
    'passeio poço azul',
    'passeio poço encantado',
    'tour morro do pai inácio',
    'passeio gruta lapa doce',
    'pacote vale do pati',
    'pacote chapada diamantina 3 dias',
    'pacote chapada diamantina 4 dias',
    'pacote chapada diamantina 5 dias',
    'pacote chapada diamantina 6 dias',
    'pacote chapada diamantina 7 dias',
    'roteiro chapada diamantina 3 dias',
    'roteiro chapada diamantina 4 dias',
    'roteiro chapada diamantina 5 dias',
    'roteiro chapada diamantina 6 dias',
    'passeio chapada diamantina preço',
    'tour chapada diamantina preço'
  ],
  FOREIGN: [
    'chapada diamantina brazil',
    'chapada diamantina national park',
    'chapada diamantina tours',
    'chapada diamantina travel',
    'chapada diamantina trekking',
    'chapada diamantina hiking',
    'vale do pati trek',
    'lençóis bahia brazil',
    'best hikes chapada diamantina',
    'waterfalls chapada diamantina'
  ],
  BLOG_SEO: [
    'o que fazer na chapada diamantina',
    'melhores passeios chapada diamantina',
    'roteiro chapada diamantina',
    'roteiro chapada diamantina 3 dias',
    'roteiro chapada diamantina 5 dias',
    'quanto custa viajar para chapada diamantina',
    'melhor época chapada diamantina',
    'dicas chapada diamantina',
    'viagem barata chapada diamantina',
    'guia completo chapada diamantina',
    'viagem solo chapada diamantina',
    'chapada diamantina para casais'
  ]
};

export const DEFAULT_KEYWORDS = [
  ...SEO_KEYWORDS.GENERAL,
  ...SEO_KEYWORDS.LOCATION.slice(0, 5),
  ...SEO_KEYWORDS.SERVICES.slice(0, 5),
  ...SEO_KEYWORDS.FOREIGN.slice(0, 3)
].join(', ');
